config/routes.rb
Rails.application.routes.draw do
  root 'inicio#index'
  resources :comentarios
  resources :pqrs
  resources :usuarios
  resources :sessions, only: [:new, :create, :destroy]
  resources :dependencia
  resources :rols
  resources :tipodocumentos
  get 'registro', to: 'usuarios#new', as: 'registro'
  get 'iniciarSesion', to: 'sessions#new', as: 'iniciarSesion'
  get 'cerrarSesion', to: 'sessions#destroy', as: 'cerrarSesion'
  get 'coment', to: 'pqrs#coment'
  post 'prueba', to: 'pqrs#prueba'
  post 'prueba_comentario', to: 'pqrs#prueba_comentario'
  post 'prueba', to: 'comentarios#prueba'
  post 'prueba_comentario', to: 'comentarios#prueba_comentario'
  post 'respuesta', to: 'pqrs#respuesta'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tipodocumento.rb
class Tipodocumento < ApplicationRecord
end

app/controllers/tipodocumentos_controller.rb
class TipodocumentosController < ApplicationController
  before_action :set_tipodocumento, only: [:show, :edit, :update, :destroy]

  # GET /tipodocumentos
  # GET /tipodocumentos.json
  def index
    @tipodocumentos = Tipodocumento.all
  end

  # GET /tipodocumentos/1
  # GET /tipodocumentos/1.json
  def show
  end

  # GET /tipodocumentos/new
  def new
    @tipodocumento = Tipodocumento.new
  end

  # GET /tipodocumentos/1/edit
  def edit
  end

  # POST /tipodocumentos
  # POST /tipodocumentos.json
  def create
    @tipodocumento = Tipodocumento.new(tipodocumento_params)

    respond_to do |format|
      if @tipodocumento.save
        format.html { redirect_to @tipodocumento, notice: 'Tipodocumento was successfully created.' }
        format.json { render :show, status: :created, location: @tipodocumento }
      else
        format.html { render :new }
        format.json { render json: @tipodocumento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipodocumentos/1
  # PATCH/PUT /tipodocumentos/1.json
  def update
    respond_to do |format|
      if @tipodocumento.update(tipodocumento_params)
        format.html { redirect_to @tipodocumento, notice: 'Tipodocumento was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipodocumento }
      else
        format.html { render :edit }
        format.json { render json: @tipodocumento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipodocumentos/1
  # DELETE /tipodocumentos/1.json
  def destroy
    @tipodocumento.destroy
    respond_to do |format|
      format.html { redirect_to tipodocumentos_url, notice: 'Tipodocumento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipodocumento
      @tipodocumento = Tipodocumento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipodocumento_params
      params.require(:tipodocumento).permit(:descripcion)
    end
end

app/helpers/tipodocumentos_helper.rb
module TipodocumentosHelper
end

app/views/tipodocumentos/_form.html.erb
<%= form_with(model: tipodocumento, local: true) do |form| %>
  <% if tipodocumento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tipodocumento.errors.count, "error") %> prohibited this tipodocumento from being saved:</h2>

      <ul>
      <% tipodocumento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tipodocumentos/edit.html.erb
<h1>Editing Tipodocumento</h1>

<%= render 'form', tipodocumento: @tipodocumento %>

<%= link_to 'Show', @tipodocumento %> |
<%= link_to 'Back', tipodocumentos_path %>

app/views/tipodocumentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tipodocumentos</h1>

<table>
  <thead>
    <tr>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tipodocumentos.each do |tipodocumento| %>
      <tr>
        <td><%= tipodocumento.descripcion %></td>
        <td><%= link_to '<i class="tiny material-icons">visibility</i>'.html_safe, tipodocumento %></td>
        <td><%= link_to '<i class="tiny material-icons">mode_edit</i>'.html_safe, edit_tipodocumento_path(tipodocumento) %></td>
        <td><%= link_to '<i class="tiny material-icons">delete</i>'.html_safe, tipodocumento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '<i class="large material-icons">add_circle</i>'.html_safe, new_tipodocumento_path, class:"btn-floating btn-large blue"  %>

app/views/tipodocumentos/new.html.erb
<h1>Nuevo Documento</h1>

<%= render 'form', tipodocumento: @tipodocumento, class: 'btn' %>

<%= link_to '<i class="large material-icons">arrow_back</i>'.html_safe, tipodocumentos_path, class:"btn-floating btn-large blue" %>

app/views/tipodocumentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripcion:</strong>
  <%= @tipodocumento.descripcion %>
</p>

<%= link_to 'Edit', edit_tipodocumento_path(@tipodocumento) %> |
<%= link_to 'Back', tipodocumentos_path %>