config/routes.rb
Rails.application.routes.draw do
  root 'inicio#index'
  resources :comentarios
  resources :pqrs
  resources :usuarios
  resources :sessions, only: [:new, :create, :destroy]
  resources :dependencia
  resources :rols
  resources :tipodocumentos
  get 'registro', to: 'usuarios#new', as: 'registro'
  get 'iniciarSesion', to: 'sessions#new', as: 'iniciarSesion'
  get 'cerrarSesion', to: 'sessions#destroy', as: 'cerrarSesion'
  get 'coment', to: 'pqrs#coment'
  post 'prueba', to: 'pqrs#prueba'
  post 'prueba_comentario', to: 'pqrs#prueba_comentario'
  post 'prueba', to: 'comentarios#prueba'
  post 'prueba_comentario', to: 'comentarios#prueba_comentario'
  post 'respuesta', to: 'pqrs#respuesta'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comentario.rb
class Comentario < ApplicationRecord
  belongs_to :pqr
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_comentario, only: [:show, :edit, :update, :destroy]

  # GET /comentarios
  # GET /comentarios.json
  def index
    @comentarios = Comentario.all
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
  end

  # GET /comentarios/new
  def new
    @comentario = Comentario.new
  end

  # GET /comentarios/1/edit
  def edit
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    @comentario = Comentario.new(comentario_params)


    respond_to do |format|
      if @comentario.save
        format.html { redirect_to @comentario, notice: 'Comentario was successfully created.' }
        format.json { render :show, status: :created, location: @comentario }
      else
        format.html { render :new }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comentarios/1
  # PATCH/PUT /comentarios/1.json
  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to @comentario, notice: 'Comentario was successfully updated.' }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario.destroy
    respond_to do |format|
      format.html { redirect_to comentarios_url, notice: 'Comentario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def prueba
    p = Pqr.find(params["pqr_id"])
    dep = Dependencium.find(params["dependencium_id"])
    p.dependencium_id = dep.id
    p.save
    render :json => p
  end

  def prueba_comentario
    c = Comentario.new
    c.comentario = params['comentario']
    c.depactual	= params['depactual']
    c.depanterior	= params['depanterior']
    c.fecha	= params['fecha']
    c.pqr_id	= params['pqr_id']
    c.save
    
    render :json => c
  end

  def comentario
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comentario_params
      params.require(:comentario).permit(:fecha, :comentario, :depactual, :depanterior, :pqr_id)
    end
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/views/comentarios/_form.html.erb
  <% if usuario_actual %>
    <%if usuario_actual.dependencium.descripcion != "usuarioNormal"%>
            <div class="int">
        <%= form_with  url: "/prueba_comentario", method: "POST" do |form| %>

          <div class="input-field">
            <%= form.label :fecha %>
            <%= form.text_field :fecha, :class => 'datepicker' %>
          </div>

          <div class="field">
            <%= form.label :comentario %>
            <%= form.text_field :comentario %>
          </div>

          <div class="field">
            <%= form.text_field :depactual, :value=>params[:depAc], :hidden=>true%>
          </div>

          <div class="field">
            <%= form.text_field :depanterior, :value=>params[:depAn], :hidden=>true%>
          </div>

          <div class="field">
            <%= form.text_field :pqr_id, :value=>params[:id], :hidden=>true%>
          </div>

          <div class="actions">
            <%= form.submit name="Crear Comentario ", :class =>"btn" %>
          </div>

        <% end %>
      </div>
    <%end%>
 
</div>
  
<% end %>

app/views/comentarios/edit.html.erb
<h1>Editing Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

app/views/comentarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comentarios</h1>

<table class="striped">
  <thead>
    <tr>
      <th>Fecha</th>
      <th>Comentario de la dependencia</th>
      <th>Depanterior</th>
      <th>depactual</th>
      <th>comentario del pqr</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.fecha %></td>
        <td><%= comentario.comentario %></td> 
        <td><%= Dependencium.find(comentario.depanterior).descripcion%></td>
        <td><%= Dependencium.find(comentario.depactual).descripcion%></td>
        <td><%= comentario.pqr.descripcion %></td>
        <td><%= link_to '<i class="tiny material-icons">visibility</i>'.html_safe, comentario %></td>
        <td><%= link_to '<i class="tiny material-icons">mode_edit</i>'.html_safe, edit_comentario_path(comentario) %></td>
        <td><%= link_to '<i class="tiny material-icons">delete</i>'.html_safe, comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comentario', new_comentario_path %>

app/views/comentarios/new.html.erb
<h1>New Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Back', comentarios_path %>

app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha:</strong>
  <%= @comentario.fecha %>
</p>

<p>
  <strong>Comentario:</strong>
  <%= @comentario.comentario %>
</p>

<p>
  <strong>Depactual:</strong>
  <%= @comentario.depactual %>
</p>

<p>
  <strong>Depanterior:</strong>
  <%= @comentario.depanterior %>
</p>

<p>
  <strong>Pqr:</strong>
  <%= @comentario.pqr.descripcion %>
</p>


<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>