config/routes.rb
Rails.application.routes.draw do
  root 'inicio#index'
  resources :comentarios
  resources :pqrs
  resources :usuarios
  resources :sessions, only: [:new, :create, :destroy]
  resources :dependencia
  resources :rols
  resources :tipodocumentos
  get 'registro', to: 'usuarios#new', as: 'registro'
  get 'iniciarSesion', to: 'sessions#new', as: 'iniciarSesion'
  get 'cerrarSesion', to: 'sessions#destroy', as: 'cerrarSesion'
  get 'coment', to: 'pqrs#coment'
  post 'prueba', to: 'pqrs#prueba'
  post 'prueba_comentario', to: 'pqrs#prueba_comentario'
  post 'prueba', to: 'comentarios#prueba'
  post 'prueba_comentario', to: 'comentarios#prueba_comentario'
  post 'respuesta', to: 'pqrs#respuesta'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pqr.rb
class Pqr < ApplicationRecord
  belongs_to :usuario
  belongs_to :dependencium
end

app/controllers/pqrs_controller.rb
class PqrsController < ApplicationController
  before_action :set_pqr, only: [:show, :edit, :update, :destroy]

  # GET /pqrs
  # GET /pqrs.json
  def index 
    if usuario_actual 
      if usuario_actual.dependencium.descripcion == "usuarioNormal"
          @pqrs = Pqr.where(usuario: usuario_actual.id)
      elsif usuario_actual.rol.descripcion == "Super Admin"
        @pqrs = Pqr.all
      else
        @pqrs = Pqr.where(dependencium: usuario_actual.dependencium)
      end

      if usuario_actual.dependencium.descripcion == "Juridica"
        @pqrs = Pqr.where(dependencium: usuario_actual.dependencium)
      end

      if usuario_actual.dependencium.descripcion == "Financiera"
        @pqrs = Pqr.where(dependencium: usuario_actual.dependencium)
      end

      if usuario_actual.dependencium.descripcion == "Administrativa"
        @pqrs = Pqr.where(dependencium: usuario_actual.dependencium)
      end
      
      else
      redirect_to root_url, notice: "Debes loguearte o no tienes permisos"
    end
  end

  

  # GET /pqrs/1
  # GET /pqrs/1.json
  def show
    @comentario = Comentario.new
  end

  # GET /pqrs/new
  def new
    if usuario_actual
      @pqr = Pqr.new
    else
      redirect_to root_url, notice: "Debes loguearte!"
    end
  end

  # GET /pqrs/1/edit
  def edit
  end

  # POST /pqrs
  # POST /pqrs.json
  def create
    @pqr = Pqr.new(pqr_params)
   
    #asignar a todos los pqr por defecto al director 
    if  @pqr.dependencium == nil
        @pqr.dependencium = Dependencium.find_by(descripcion: "Director")
    end

    @pqr.estado = false

    name = pqr_params["archivo"].original_filename
    path = File.join("public", "archivos", "upload", name)
    File.open(path, "wb") { |f| f.write( pqr_params["archivo"].read ) }

    @pqr.archivo = "archivos/upload/"+name

    respond_to do |format|
      if @pqr.save
       
        format.html { redirect_to @pqr, notice: 'Pqr was successfully created.' }
        format.json { render :show, status: :created, location: @pqr }
      else
        format.html { render :new }
        format.json { render json: @pqr.errors, status: :unprocessable_entity }
      end
    end
    
  end

  def prueba
    p = Pqr.find(params["pqr_id"])
    dep = Dependencium.find(params["dependencium_id"])
    ant = p.dependencium_id
    p.dependencium_id = dep.id
    p.save

    enviar = {
      id: params[:pqr_id],
      depAc: params[:dependencium_id],
      depAn: ant    }
    Rails.logger.debug "****************"
    redirect_to new_comentario_path(enviar)
    Rails.logger.debug "****************"
  end


  def prueba_comentario
    c = Comentario.new
    c.comentario = params['comentario']
    c.depactual	= params['depactual']
    c.depanterior	= params['depanterior']
    c.fecha	= params['fecha']
    c.pqr_id	= params['pqr_id']
    c.save

    p = Pqr.find(params["pqr_id"])
    dep = Dependencium.find(params["dependencium_id"])
    ant = p.dependencium_id
    p.dependencium_id = dep.id

    enviar = {
      id: params[:pqr_id],
      depAc: params[:dependencium_id],
      depAn: ant  
    }

    comentarios_path(enviar)
    
    # render :json => c
  end

  def respuesta
    r = Pqr.find(params[:pqr_id])
    r.respuesta = params[:respuesta]
    r.estado = true
    r.save

    render :json => r
  end

  def coment
  end
  # PATCH/PUT /pqrs/1
  # PATCH/PUT /pqrs/1.json
  def update
    respond_to do |format|
      if @pqr.update(pqr_params)
        format.html { redirect_to @pqr, notice: 'Pqr was successfully updated.' }
        format.json { render :show, status: :ok, location: @pqr }
      else
        format.html { render :edit }
        format.json { render json: @pqr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pqrs/1
  # DELETE /pqrs/1.json
  def destroy
    @pqr.destroy
    respond_to do |format|
      format.html { redirect_to pqrs_url, notice: 'Pqr was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pqr
      @pqr = Pqr.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pqr_params
      params.require(:pqr).permit(:fecha, :descripcion, :archivo, :estado, :usuario_id, :dependencium_id, :respuesta)
    end

end

app/helpers/pqrs_helper.rb
module PqrsHelper
end

app/views/pqrs/_form.html.erb
<%= form_with(model: pqr, local: true, multipart: true) do |form| %>
  <% if pqr.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pqr.errors.count, "error") %> prohibited this pqr from being saved:</h2>

      <ul>
      <% pqr.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="contPq">
  <div class="input-field">
    <%= form.label :fecha %>
    <%= form.text_field :fecha, :class => 'datepicker' %>
  </div>

  <div class="input-field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion %>
  </div>

  <div class="input-field">
    <%= form.file_field :archivo %>
  </div>
  
    <div class="field" hidden>
      <%= form.label :usuario_id %>
      <%= form.text_field :usuario_id, value: usuario_actual.id %>
    </div>
  
    <% if usuario_actual && usuario_actual.rol.descripcion == "Super Admin"%>
      <div class="input-field">
        <%= form.label :Dependencia, {}, {:class => "arriba"} %>
        <%= form.select :dependencium_id, Dependencium.all.collect{ |a| [ a.descripcion, a.id] }, {}, {:class => 'browser-default'} %>
      </div>
    <% end %>
    
  <div class="field">
    <%= form.submit "Crear" %>
  </div>

  </div>
  
<% end %>

app/views/pqrs/edit.html.erb
<h1>Editing Pqr</h1>

<%= render 'form', pqr: @pqr %>

<%= link_to 'Show', @pqr %> |
<%= link_to 'Back', pqrs_path %>

app/views/pqrs/index.html.erb
<p id="notice"><%= notice %></p>

<table class="striped">

  <thead>
    
    <tr>
      <th>Fecha</th>
      <th>Descripcion</th>
      <th>Archivo</th>
      <th>Estado</th>
      <th>Usuario</th>
      <%if usuario_actual.rol.descripcion == "Super Admin"%>
      <th>Dependencium</th>
      <% end %>
      <th>Respuesta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pqrs.each do |pqr| %>
        <tr>
            <td><%= pqr.fecha %></td>
            <td><%= pqr.descripcion %></td>
            <td>
              <a href="/<%= pqr.archivo %>" target="_blank" >Archivo</a>
            </td>
            <% if pqr.estado %>
              <td>Respondido</td>
            <% else %>
              <td>Sin respuesta</td>
            <% end %>
          <td><%= pqr.usuario.nombre %></td>
          <%if usuario_actual.rol.descripcion == "Super Admin"%>
          <td><%= pqr.dependencium.descripcion %></td>
          <% end %>
          <td><%= pqr.respuesta %></td>
        <%if usuario_actual.dependencium.descripcion != "usuarioNormal"%>
          <td><%= link_to '<i class="tiny material-icons">visibility</i>'.html_safe, pqr %></td>
          <td><%= link_to '<i class="tiny material-icons">mode_edit</i>'.html_safe, edit_pqr_path(pqr) %></td>
          <td><%= link_to '<i class="tiny material-icons">delete</i>'.html_safe, pqr, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
     
  </tbody>
</table>

<br>
  <% if usuario_actual.dependencium.descripcion == "usuarioNormal"%>
    <%= link_to 'New Pqr', new_pqr_path , :class => "btn" %>
    <a href = "/" class="btn"> Inicio </a>
  <% end %>

app/views/pqrs/new.html.erb
<h1>New Pqr</h1>

<%= render 'form', pqr: @pqr %>

<%= link_to 'Atras', pqrs_path , :class => "btn"  %>

app/views/pqrs/show.html.erb
<%= content_for(:body_attributes, 'data-no-turbolink') %>

<p id="notice">
  <%= notice %>
</p>
<div class="">
  <!-- <p>
    <strong>Fecha:</strong>
    <%= @pqr.fecha %>
  </p>

  <p>
    <strong>Descripcion:</strong>
    <%= @pqr.descripcion %>
  </p>

  <p>
    <strong>Archivo:</strong>
    <%= @pqr.archivo %>
  </p>

  <p>
    <strong>Estado:</strong>
    <%= @pqr.estado %>
  </p>

  <p>
    <strong>Usuario:</strong>
    <%= @pqr.usuario.nombre %>
  </p>

  <p>
    <strong>Dependencium:</strong>
    <%= @pqr.dependencium.descripcion %>
  </p>

  <p>
    <strong>Respuesta:</strong>
    <%= @pqr.respuesta %>
  </p>-->

</div>
<div class="content">

  <% if usuario_actual %>
  |<% if @pqr.estado != true %>
    <%if usuario_actual.dependencium.descripcion != "usuarioNormal"%>
      <div class="int">
        <%= form_with url: "/prueba", method: "POST" do |form| %>

          <div class="input-field">
            <input type="number" value="<%=@pqr.id %>" name="pqr_id" hidden />
            <%= form.select :dependencium_id, Dependencium.all.collect{ |a| [ a.descripcion, a.id] }, {}, {:class => 'browser-default'} %>
          </div>

        <%= form.submit name="cambiar dependencia", :class =>"btn Cam" %>
      <% end %>
      </div>
    <%end%>
  <% end %>

  <% if usuario_actual %>
  <% if @pqr.estado != true %>
    <%if usuario_actual.rol.descripcion == "Super Admin" %>
      <div class="int">
        <%= form_with  url: "/respuesta", method: "POST" do |form| %>
          <div class="field">
          
          <input type="number" value="<%=@pqr.id %>" name="pqr_id" hidden />
            <%= form.label :respuesta %>
            <%= form.text_field :respuesta %>
          </div>

          <div class="actions">
            <%= form.submit name= "respuesta", :class =>"btn", :id => "coment" %>
          </div>
        <% end %>
      </div>
    <%end%>
  <%end%>
|<%end%>
<%end%>
</div>

<%= link_to 'Edit', edit_pqr_path(@pqr) %> |
<%= link_to 'Back', pqrs_path %>