config/routes.rb
Rails.application.routes.draw do
  root 'inicio#index'
  resources :comentarios
  resources :pqrs
  resources :usuarios
  resources :sessions, only: [:new, :create, :destroy]
  resources :dependencia
  resources :rols
  resources :tipodocumentos
  get 'registro', to: 'usuarios#new', as: 'registro'
  get 'iniciarSesion', to: 'sessions#new', as: 'iniciarSesion'
  get 'cerrarSesion', to: 'sessions#destroy', as: 'cerrarSesion'
  get 'coment', to: 'pqrs#coment'
  post 'prueba', to: 'pqrs#prueba'
  post 'prueba_comentario', to: 'pqrs#prueba_comentario'
  post 'prueba', to: 'comentarios#prueba'
  post 'prueba_comentario', to: 'comentarios#prueba_comentario'
  post 'respuesta', to: 'pqrs#respuesta'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comentario.rb
class Comentario < ApplicationRecord
  belongs_to :pqr
end

app/models/dependencium.rb
class Dependencium < ApplicationRecord
end

app/models/pqr.rb
class Pqr < ApplicationRecord
  belongs_to :usuario
  belongs_to :dependencium
end

app/models/rol.rb
class Rol < ApplicationRecord
end

app/models/tipodocumento.rb
class Tipodocumento < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  belongs_to :rol
  belongs_to :dependencium
  belongs_to :tipodocumento
  has_secure_password
  validates :email, presence: true, uniqueness: true
end

app/controllers/coment_controller.rb
class ComentController < ApplicationController

end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
    def index
        render "index"
    end
end

app/controllers/pqrs_controller.rb
class PqrsController < ApplicationController
  before_action :set_pqr, only: [:show, :edit, :update, :destroy]

  # GET /pqrs
  # GET /pqrs.json
  def index 
    if usuario_actual 
      if usuario_actual.dependencium.descripcion == "usuarioNormal"
          @pqrs = Pqr.where(usuario: usuario_actual.id)
      elsif usuario_actual.rol.descripcion == "Super Admin"
        @pqrs = Pqr.all
      else
        @pqrs = Pqr.where(dependencium: usuario_actual.dependencium)
      end

      if usuario_actual.dependencium.descripcion == "Juridica"
        @pqrs = Pqr.where(dependencium: usuario_actual.dependencium)
      end

      if usuario_actual.dependencium.descripcion == "Financiera"
        @pqrs = Pqr.where(dependencium: usuario_actual.dependencium)
      end

      if usuario_actual.dependencium.descripcion == "Administrativa"
        @pqrs = Pqr.where(dependencium: usuario_actual.dependencium)
      end
      
      else
      redirect_to root_url, notice: "Debes loguearte o no tienes permisos"
    end
  end

  

  # GET /pqrs/1
  # GET /pqrs/1.json
  def show
    @comentario = Comentario.new
  end

  # GET /pqrs/new
  def new
    if usuario_actual
      @pqr = Pqr.new
    else
      redirect_to root_url, notice: "Debes loguearte!"
    end
  end

  # GET /pqrs/1/edit
  def edit
  end

  # POST /pqrs
  # POST /pqrs.json
  def create
    @pqr = Pqr.new(pqr_params)
   
    #asignar a todos los pqr por defecto al director 
    if  @pqr.dependencium == nil
        @pqr.dependencium = Dependencium.find_by(descripcion: "Director")
    end

    @pqr.estado = false

    name = pqr_params["archivo"].original_filename
    path = File.join("public", "archivos", "upload", name)
    File.open(path, "wb") { |f| f.write( pqr_params["archivo"].read ) }

    @pqr.archivo = "archivos/upload/"+name

    respond_to do |format|
      if @pqr.save
       
        format.html { redirect_to @pqr, notice: 'Pqr was successfully created.' }
        format.json { render :show, status: :created, location: @pqr }
      else
        format.html { render :new }
        format.json { render json: @pqr.errors, status: :unprocessable_entity }
      end
    end
    
  end

  def prueba
    p = Pqr.find(params["pqr_id"])
    dep = Dependencium.find(params["dependencium_id"])
    ant = p.dependencium_id
    p.dependencium_id = dep.id
    p.save

    enviar = {
      id: params[:pqr_id],
      depAc: params[:dependencium_id],
      depAn: ant    }
    Rails.logger.debug "****************"
    redirect_to new_comentario_path(enviar)
    Rails.logger.debug "****************"
  end


  def prueba_comentario
    c = Comentario.new
    c.comentario = params['comentario']
    c.depactual	= params['depactual']
    c.depanterior	= params['depanterior']
    c.fecha	= params['fecha']
    c.pqr_id	= params['pqr_id']
    c.save

    p = Pqr.find(params["pqr_id"])
    dep = Dependencium.find(params["dependencium_id"])
    ant = p.dependencium_id
    p.dependencium_id = dep.id

    enviar = {
      id: params[:pqr_id],
      depAc: params[:dependencium_id],
      depAn: ant  
    }

    comentarios_path(enviar)
    
    # render :json => c
  end

  def respuesta
    r = Pqr.find(params[:pqr_id])
    r.respuesta = params[:respuesta]
    r.estado = true
    r.save

    render :json => r
  end

  def coment
  end
  # PATCH/PUT /pqrs/1
  # PATCH/PUT /pqrs/1.json
  def update
    respond_to do |format|
      if @pqr.update(pqr_params)
        format.html { redirect_to @pqr, notice: 'Pqr was successfully updated.' }
        format.json { render :show, status: :ok, location: @pqr }
      else
        format.html { render :edit }
        format.json { render json: @pqr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pqrs/1
  # DELETE /pqrs/1.json
  def destroy
    @pqr.destroy
    respond_to do |format|
      format.html { redirect_to pqrs_url, notice: 'Pqr was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pqr
      @pqr = Pqr.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pqr_params
      params.require(:pqr).permit(:fecha, :descripcion, :archivo, :estado, :usuario_id, :dependencium_id, :respuesta)
    end

end

app/controllers/rols_controller.rb
class RolsController < ApplicationController
  before_action :set_rol, only: [:show, :edit, :update, :destroy]

  # GET /rols
  # GET /rols.json
  def index
    @rols = Rol.all
  end

  # GET /rols/1
  # GET /rols/1.json
  def show
  end

  # GET /rols/new
  def new
    @rol = Rol.new
  end

  # GET /rols/1/edit
  def edit
  end

  # POST /rols
  # POST /rols.json
  def create
    @rol = Rol.new(rol_params)

    respond_to do |format|
      if @rol.save
        format.html { redirect_to @rol, notice: 'Rol was successfully created.' }
        format.json { render :show, status: :created, location: @rol }
      else
        format.html { render :new }
        format.json { render json: @rol.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rols/1
  # PATCH/PUT /rols/1.json
  def update
    respond_to do |format|
      if @rol.update(rol_params)
        format.html { redirect_to @rol, notice: 'Rol was successfully updated.' }
        format.json { render :show, status: :ok, location: @rol }
      else
        format.html { render :edit }
        format.json { render json: @rol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rols/1
  # DELETE /rols/1.json
  def destroy
    @rol.destroy
    respond_to do |format|
      format.html { redirect_to rols_url, notice: 'Rol was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rol
      @rol = Rol.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rol_params
      params.require(:rol).permit(:descripcion)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coment_helper.rb
module ComentHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/dependencia_helper.rb
module DependenciaHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/pqrs_helper.rb
module PqrsHelper
end

app/helpers/rols_helper.rb
module RolsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">

<head>
  <title>FinalArquitectura</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<nav>
    <div class="nav-wrapper">
        <a href="" class="brand-logo center">PQR's</a>
        <ul class="Bnav">  
        <% if usuario_actual %>
            <li> Usuario: <%= usuario_actual.nombre %> - <%= usuario_actual.dependencium.descripcion %></li>
            <li> <%= link_to "Cerrar sesión" , "cerrarSesion" %></li>
        <% end %>
        </ul>
    </div>
</nav>
<% if usuario_actual %>
  <% if usuario_actual.rol.descripcion == "Super Admin" %>
    <ul class=" acorh">
      <li><a href="/">Inicio</a></li>
      <li><%= link_to 'Listar Pqr', pqrs_path %></li>
      <li><%= link_to 'Listar usuarios', usuarios_path %></li>
      <li><%= link_to 'Listar comentarios', comentarios_path %></li>
        <li><a href="#">Gestion De Rol</a>
          <ul>
            <li><a href="rols/new">Nuevo Rol</a></li>
            <li><%= link_to 'Listar Rols', rols_path %></li>
          </ul>
        </li>
    </ul>
  <% end %>
<% end %>


<% if usuario_actual && usuario_actual.dependencium.descripcion != "usuarioNormal"%>
  <% if usuario_actual.rol.descripcion != "Super Admin"%>
    <ul class= "acorh">
      <li><a href="/">Inicio</a></li>
      <li><%= link_to 'Listar Pqr', pqrs_path %></li>
      <li><%= link_to 'Listar comentarios', comentarios_path%></li>
    </ul>
    
  <% end %>
<% end %>


<%= yield %>

<li><a href="/">Inicio</a></li>
</body>

</html>